#!/usr/bin/env python3
"""
generate_android.py — components.yaml + tokens.css → Android XML resources

Generates:
  - exports/android/colors.xml  (from tokens.css)
  - exports/android/styles.xml  (from components.yaml)

Usage:
  python scripts/design-system/generate_android.py
  python scripts/design-system/generate_android.py --check
"""

import argparse
import re
import sys
from pathlib import Path

import yaml  # type: ignore

ROOT = Path(__file__).resolve().parent.parent.parent
TOKENS_CSS = ROOT / "design-system" / "tokens" / "tokens.css"
COMPONENTS_YAML = ROOT / "design-system" / "components" / "components.yaml"
OUTPUT_DIR = ROOT / "design-system" / "exports" / "android"


def parse_tokens_css() -> dict[str, str]:
    """Parse tokens.css and return {name: value} mapping."""
    tokens = {}
    if not TOKENS_CSS.exists():
        return tokens

    css = TOKENS_CSS.read_text()
    token_re = re.compile(r'--([a-z][a-z0-9-]*):\s*([^;]+);')
    for match in token_re.finditer(css):
        name = match.group(1)
        value = match.group(2).strip()
        tokens[name] = value
    return tokens


def css_hex_to_android_hex(hex_color: str, alpha_hex_map: dict = None) -> str:
    """
    Convert CSS color to Android resource format.

    #6C5CE7 → #6C5CE7 (same)
    rgba(108, 92, 231, 0.15) → #266C5CE7 (ARGB)
    """
    hex_color = hex_color.strip()
    if hex_color.startswith("#"):
        return hex_color

    rgba_match = re.match(
        r'rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([0-9.]+))?\s*\)',
        hex_color
    )
    if rgba_match:
        r, g, b = int(rgba_match.group(1)), int(rgba_match.group(2)), int(rgba_match.group(3))
        a = rgba_match.group(4)
        if a is not None:
            alpha = round(float(a) * 255)
            return f"#{alpha:02X}{r:02X}{g:02X}{b:02X}"
        else:
            return f"#{r:02X}{g:02X}{b:02X}"

    return hex_color


def generate_colors_xml(tokens: dict) -> str:
    """Generate Android colors.xml from tokens."""
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!--',
        '  colors.xml — Android Color Resources',
        '',
        '  AUTO-GENERATED by scripts/design-system/generate_android.py',
        '  from tokens/tokens.css.',
        '  DO NOT EDIT MANUALLY. Modify tokens/tokens.css instead.',
        '-->',
        '<resources>',
    ]

    # Map token names to Android resource names
    for var_name, value in sorted(tokens.items()):
        if "shadow" in var_name or "transition" in var_name or "z-" in var_name:
            continue  # Skip non-color tokens

        android_name = var_name.replace("-", "_")
        android_color = css_hex_to_android_hex(value)

        # Add comment for categories
        if var_name.startswith("color-"):
            if "color-primary:" in f"{var_name}:":
                lines.append("  <!-- ── Brand Colors ───────────────────────────────────────── -->")
            elif "color-rating:" in f"{var_name}:":
                lines.append("  <!-- ── Semantic Colors ─────────────────────────────────────── -->")
        elif var_name.startswith("bg-"):
            if "bg-outer:" in f"{var_name}:":
                lines.append("  <!-- ── Backgrounds ─────────────────────────────────────────── -->")
        elif var_name.startswith("border") or var_name.startswith("surface"):
            if "surface-subtle:" in f"{var_name}:":
                lines.append("  <!-- ── Borders & Surfaces ──────────────────────────────────── -->")
        elif var_name.startswith("text-"):
            if "text-primary:" in f"{var_name}:":
                lines.append("  <!-- ── Text ────────────────────────────────────────────────── -->")

        lines.append(f'  <color name="{android_name}">{android_color}</color>')

    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def generate_styles_xml(components: dict) -> str:
    """Generate Android styles.xml from components.yaml."""
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!--',
        '  styles.xml — Android Component Styles',
        '',
        '  AUTO-GENERATED by scripts/design-system/generate_android.py',
        '  from components/components.yaml.',
        '  DO NOT EDIT MANUALLY. Modify components/components.yaml instead.',
        '-->',
        '<resources>',
    ]

    lines.append("  <!-- ── Buttons ─────────────────────────────────────────────── -->")

    for comp_name, comp in components.items():
        base = comp.get("base", {})
        description = comp.get("description", "")

        # Generate an appropriate parent theme
        parent = "Widget.MaterialComponents.Button"
        style_name = comp_name.replace("-", " ").title().replace(" ", ".")
        full_name = f"DramaFlow.{style_name}"

        if "outline" in comp_name.lower():
            parent = "Widget.MaterialComponents.Button.OutlinedButton"
        elif "card" in comp_name.lower():
            parent = "Widget.MaterialComponents.CardView"

        lines.append("")
        if description:
            lines.append(f"  <!-- {description} -->")
        lines.append(f'  <style name="{full_name}" parent="{parent}">')

        # Map component properties to Android attributes
        for prop, value in base.items():
            if prop in ("description", "figma_component_id", "extends", "parts", "states"):
                continue

            attr = _map_to_android_attr(prop, value)
            if attr:
                lines.append(f"    {attr}")

        lines.append("  </style>")

    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def _map_to_android_attr(prop: str, value) -> str | None:
    """Map a component property to an Android XML attribute."""
    # Resolve token references
    resolved = str(value)
    resolved = re.sub(r'\{([^}]+)\}', lambda m: _token_to_android_ref(m.group(1)), resolved)

    # Height → layout_height
    if prop == "height":
        return f'<item name="android:minHeight">{resolved}</item>'
    if prop == "padding":
        parts = resolved.split()
        if len(parts) == 1:
            return f'<item name="android:padding">{parts[0]}</item>'
        # Approximate: just use unified padding
        return f'<item name="android:padding">{parts[0]}</item>'
    if prop == "border-radius":
        return f'<item name="cornerRadius">{resolved}</item>'
    if prop == "border":
        if "solid" in str(value):
            return f'<item name="strokeColor">{resolved}</item>'

    # Skip complex properties
    return None


def _token_to_android_ref(ref: str) -> str:
    """Convert token reference to Android resource reference."""
    kebab = ref.replace(".", "_")
    kebab = re.sub(r'([A-Z])', r'_\1', kebab).lower()
    kebab = kebab.replace("__", "_")
    return f"@color/{kebab}"


def main():
    parser = argparse.ArgumentParser(
        description="Generate Android XML resources from design-system"
    )
    parser.add_argument("--check", action="store_true",
                        help="Validate existing files")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be generated without writing")
    args = parser.parse_args()

    print("🤖  Design System → Android XML")
    print(f"    Output directory: {OUTPUT_DIR}")
    print()

    # Generate colors.xml
    tokens = parse_tokens_css()
    if tokens:
        print(f"    Parsed {len(tokens)} tokens from tokens.css")
        colors_xml = generate_colors_xml(tokens)
        if args.dry_run:
            print("\n--- colors.xml preview (first 20 lines) ---")
            for line in colors_xml.splitlines()[:20]:
                print(line)
        else:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            (OUTPUT_DIR / "colors.xml").write_text(colors_xml)
            print(f"    ✅ Written: colors.xml ({len(colors_xml.splitlines())} lines)")
    else:
        print("    ⚠️  No tokens found in tokens.css")

    # Generate styles.xml
    if COMPONENTS_YAML.exists():
        with open(COMPONENTS_YAML) as f:
            data = yaml.safe_load(f)
        components = data.get("components", {})
        print(f"    Parsed {len(components)} components from components.yaml")

        styles_xml = generate_styles_xml(components)
        if args.dry_run:
            print("\n--- styles.xml preview (first 30 lines) ---")
            for line in styles_xml.splitlines()[:30]:
                print(line)
        else:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            (OUTPUT_DIR / "styles.xml").write_text(styles_xml)
            print(f"    ✅ Written: styles.xml ({len(styles_xml.splitlines())} lines)")
    else:
        print(f"    ⚠️  components.yaml not found")

    print()


if __name__ == "__main__":
    main()
